// <auto-generated />
using ApartmentManagement.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ApartmentManagement.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261004120000_AddFacilityBookingInvoiceReference")]
    partial class AddFacilityBookingInvoiceReference
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // The migration applies a nullable booking reference and a unique
            // index; the current runtime model is maintained in AppDbContext.
        }
    }
}
