using ApartmentManagement.Api.Data;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ApartmentManagement.Api.Migrations
{
    /// <summary>
    /// Adds durable, operational audit state for the maintenance agent workflow.
    /// The guarded SQL also supports databases created with the previous setup-db endpoint.
    /// </summary>
    [DbContext(typeof(AppDbContext))]
    [Migration("20260926110000_AddAgentWorkflowAuditSteps")]
    public partial class AddAgentWorkflowAuditSteps : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS ""AgentWorkflows"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ""MaintenanceId"" integer NOT NULL REFERENCES ""Maintenances"" (""Id"") ON DELETE CASCADE,
                    ""Objective"" text NOT NULL DEFAULT '', ""Plan"" text NOT NULL DEFAULT '',
                    ""CurrentStep"" text NOT NULL DEFAULT '', ""CompletedSteps"" text NOT NULL DEFAULT '',
                    ""ToolResults"" text NOT NULL DEFAULT '', ""ValidationResults"" text NOT NULL DEFAULT '',
                    ""Errors"" text NOT NULL DEFAULT '', ""ApprovalStatus"" text NOT NULL DEFAULT 'Pending',
                    ""ApprovalUser"" text NOT NULL DEFAULT '', ""ApprovalTime"" timestamp with time zone NULL,
                    ""FinalOutcome"" text NOT NULL DEFAULT '', ""CreatedAt"" timestamp with time zone NOT NULL,
                    ""UpdatedAt"" timestamp with time zone NOT NULL
                );
                ALTER TABLE ""AgentWorkflows"" ADD COLUMN IF NOT EXISTS ""Status"" text NOT NULL DEFAULT 'Running';
                ALTER TABLE ""AgentWorkflows"" ADD COLUMN IF NOT EXISTS ""ApprovalNote"" text NOT NULL DEFAULT '';
                ALTER TABLE ""AgentWorkflows"" ADD COLUMN IF NOT EXISTS ""IsSafeFailure"" boolean NOT NULL DEFAULT false;
                CREATE INDEX IF NOT EXISTS ""IX_AgentWorkflows_MaintenanceId"" ON ""AgentWorkflows"" (""MaintenanceId"");

                CREATE TABLE IF NOT EXISTS ""AgentWorkflowSteps"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ""AgentWorkflowId"" integer NOT NULL REFERENCES ""AgentWorkflows"" (""Id"") ON DELETE CASCADE,
                    ""Sequence"" integer NOT NULL, ""AgentRole"" text NOT NULL, ""Action"" text NOT NULL,
                    ""Status"" text NOT NULL, ""ToolName"" text NOT NULL, ""InputSummary"" text NOT NULL,
                    ""OutputSummary"" text NOT NULL, ""ValidationResult"" text NOT NULL,
                    ""DurationMilliseconds"" integer NOT NULL, ""CreatedAt"" timestamp with time zone NOT NULL
                );
                CREATE INDEX IF NOT EXISTS ""IX_AgentWorkflowSteps_AgentWorkflowId"" ON ""AgentWorkflowSteps"" (""AgentWorkflowId"");
            ");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("DROP TABLE IF EXISTS \"AgentWorkflowSteps\";");
        }
    }
}

